backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/img"
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Screens"
        name: "screens"
        widget: "list"
        field: {label: Image, name: image, widget: image}

      # layout: project
      # title: Barcelona
      # name: Decidim Barcelona
      # client: Barcelona City Council
      # description: The city of Barcelona is developing its own open source participation platform. We are the responsibles of the UX and design for 2018. We have also designed and developed the accountability module and the global accountability section, which shows all accountability initiatives across the City Council.
      # services:
      #   - ux
      #   - dev
      #   - data
      # technology:
      #   - Ruby On Rails
      #   - Decidim
      # img: projects/screens/BCN-Decidim-0.jpg
      # screens:
      #   - projects/screens/BCN-Decidim-1.jpg
      #   - projects/screens/BCN-Decidim-2.jpg
      #   - projects/screens/BCN-Decidim-3.jpg
      #   - projects/screens/BCN-Decidim-4.jpg
      #   - projects/screens/BCN-Decidim-5.jpg
      #   - projects/screens/BCN-Decidim-6.jpg
      # screen_1: projects/screens/panama-papers-1.jpg
      # public_url: https://decidim.barcelona/
      # client_url: https://ajuntament.barcelona.cat/
      # weight: 3
